### ISSUE TITLE
Required Packages Missing

### ISSUE THREAD

**Issue by flycal6** [Drop-Project/Integration-Wingpanel#7]
`wingpanel-2.0`, `libnotify`, and `drop-1.0` packages not found.  

Looking through apt, it appears `wingpanel-2.0`may now be `libwingpanel-2.0.0` and `libnotify` > `libnotify4`.  I couldn't find anything similar to `drop-1.0`.

**Comment by Philip-Scott** [comment]
Nop, the dependencies are actually correct :) 

This project is the Wingpanel Indicator for Loki for this: https://github.com/Drop-Project/Vala-Server. You require that Vala-Server installed first
